namespace AnkiIO;

/// <summary>Represents one study direction generated from an <see cref="AnkiNote"/>.</summary>
/// <remarks>
/// A note stores facts; a card is the question/answer view Anki schedules. A Basic note normally owns one card, a
/// Basic-and-reversed note owns two, and a Cloze note owns one card per distinct positive cloze index. Most callers should
/// obtain cards from <see cref="AnkiNote.Cards"/> after adding a note to a deck instead of constructing cards directly.
///
/// <para>
/// <see cref="DeckId"/>, <see cref="Scheduling"/>, <see cref="Flag"/>, and <see cref="ReviewHistory"/> are mutable advanced
/// state. AnkiIO does not run Anki's scheduler; it only models and validates persisted values. Call
/// <see cref="AnkiValidator.Validate(AnkiDeck)"/> before export. Instances and their history lists are not thread-safe.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var deck = new AnkiDeck("Vocabulary");
/// var note = deck.AddBasicNote("Haus", "house");
/// var card = note.Cards.Single();
/// card.Flag = 1; // red: a card-level reminder to revisit this item
/// </code>
/// </example>
public sealed class AnkiCard
{
    private AnkiScheduling scheduling;

    /// <summary>Initializes an unattached card for an importer or format adapter.</summary>
    /// <param name="id">The persisted card ID. It must be unique across the exported graph.</param>
    /// <param name="noteId">The ID of the note that generated this card.</param>
    /// <param name="deckId">The ID of the deck in which Anki should place this card.</param>
    /// <param name="templateOrdinal">
    /// For a standard note type, the zero-based index in <see cref="AnkiNoteType.Templates"/>. For Cloze, cloze marker
    /// <c>c1</c> maps to ordinal 0, <c>c2</c> to ordinal 1, and so on.
    /// </param>
    /// <param name="scheduling">
    /// Non-null persisted scheduler state. Use <see cref="AnkiScheduling.New"/> unless importing verified existing state.
    /// The object is retained by reference rather than copied.
    /// </param>
    /// <remarks>
    /// This constructor does not attach the card to a note or deck. Ordinary creation through <see cref="AnkiDeck.AddNote"/>
    /// establishes those relationships and assigns safe new-card scheduling automatically.
    /// </remarks>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="templateOrdinal"/> is negative.</exception>
    /// <exception cref="ArgumentNullException"><paramref name="scheduling"/> is <see langword="null"/>.</exception>
    public AnkiCard(long id, long noteId, long deckId, int templateOrdinal, AnkiScheduling scheduling)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(templateOrdinal);

        Id = id;
        NoteId = noteId;
        DeckId = deckId;
        TemplateOrdinal = templateOrdinal;
        this.scheduling = scheduling ?? throw new ArgumentNullException(nameof(scheduling));
    }

    /// <summary>Gets the persisted identity Anki uses to distinguish this card from every other card.</summary>
    /// <value>The fixed ID supplied by an importer or generated by AnkiIO.</value>
    /// <remarks>
    /// Preserve this value during updates so Anki can recognize the same card. Supplying explicit IDs makes collision
    /// avoidance the caller's responsibility; <see cref="AnkiValidator"/> reports duplicate card IDs in a deck graph.
    /// </remarks>
    public long Id { get; }

    /// <summary>Gets the ID of the note whose fields and template render this card.</summary>
    /// <value>A fixed note ID that should match an <see cref="AnkiNote.Id"/> in the same object graph.</value>
    public long NoteId { get; }

    /// <summary>Gets or sets the deck in which Anki should place this individual card.</summary>
    /// <value>A deck ID, normally the ID of the deck that owns the note.</value>
    /// <remarks>
    /// Anki permits sibling cards from one note to live in different decks. Changing this value models that placement; it
    /// does not move the note between <see cref="AnkiDeck.Notes"/> collections or create a missing deck. Validate the complete
    /// graph before export so the referenced deck can be checked.
    /// </remarks>
    public long DeckId { get; set; }

    /// <summary>Gets which template or Cloze deletion generated this card.</summary>
    /// <value>
    /// A fixed zero-based template index for standard notes, or one less than the positive Cloze index for Cloze notes.
    /// </value>
    /// <remarks>
    /// For example, the second template and <c>{{c2::answer}}</c> both use ordinal 1. An ordinal outside the note type's
    /// available templates or current cloze indexes represents stale/corrupt state and is rejected by validation.
    /// </remarks>
    public int TemplateOrdinal { get; }

    /// <summary>Gets or replaces the complete persisted scheduler state for this card.</summary>
    /// <value>A non-null immutable value object; generated cards start with <see cref="AnkiScheduling.New"/>.</value>
    /// <remarks>
    /// Replace this only when importing or deliberately preserving known scheduling data. Queue/type combinations and the
    /// units of <see cref="AnkiScheduling.Due"/> vary by state. AnkiIO validates combinations but does not calculate the next
    /// interval, apply deck options, or run FSRS.
    /// </remarks>
    /// <exception cref="ArgumentNullException">The assigned value is <see langword="null"/>.</exception>
    public AnkiScheduling Scheduling
    {
        get => scheduling;
        set => scheduling = value ?? throw new ArgumentNullException(nameof(value), "Scheduling cannot be null.");
    }

    /// <summary>Gets or sets the single user-visible color flag attached to this card.</summary>
    /// <value>Anki's numeric flag code; valid persisted values are 0 through 7 and a new card starts at 0.</value>
    /// <remarks>
    /// Flags are card-level reminders shown during review and in the browser; unlike note tags, flagging one sibling does
    /// not flag the others. Anki lets users rename flag labels, but the persisted numeric/color mapping remains:
    /// <list type="table">
    /// <listheader><term>Value</term><description>Default flag</description></listheader>
    /// <item><term>0</term><description>No flag</description></item>
    /// <item><term>1</term><description>Red</description></item>
    /// <item><term>2</term><description>Orange</description></item>
    /// <item><term>3</term><description>Green</description></item>
    /// <item><term>4</term><description>Blue</description></item>
    /// <item><term>5</term><description>Pink</description></item>
    /// <item><term>6</term><description>Turquoise</description></item>
    /// <item><term>7</term><description>Purple</description></item>
    /// </list>
    /// The legacy card column stores the flag in its low three bits. The setter deliberately accepts an <see cref="int"/>
    /// so importers can represent malformed source data and obtain a complete diagnostic report; it does not silently mask
    /// high bits. <see cref="AnkiValidator.Validate(AnkiDeck)"/> reports <c>ANKI032</c> for values outside 0-7, and validated
    /// writers refuse to export that graph. Validate after assigning imported state.
    ///
    /// <para>
    /// Use tags when an annotation should apply to every card generated by a note or when multiple labels are needed; a
    /// card can have only one flag.
    /// </para>
    /// </remarks>
    public int Flag { get; set; }

    /// <summary>Gets answer events associated with this card.</summary>
    /// <value>A live mutable list owned by the card; append records in chronological or persisted ID order.</value>
    /// <remarks>
    /// Native AnkiIO JSON preserves this list and the legacy package writer emits it. The current legacy APKG reader does
    /// not reconstruct existing review-log rows, so APKG read-modify-write is not a lossless history migration. Adding a log
    /// does not update <see cref="Scheduling"/> automatically, and changing scheduling does not synthesize a log. Treat both
    /// as advanced imported state and keep them consistent yourself.
    /// </remarks>
    public IList<AnkiReviewLog> ReviewHistory { get; } = new List<AnkiReviewLog>();
}
